### ISSUE TITLE
Unable to build android apk

### ISSUE THREAD

**Issue by justnajm** [aduros/flambe#280]
Hi,

Thanks for great tool like flambe

For some reason I am unable to build apk file, I have tried multiple things such as downloading new air sdk, using adob air gaming sdk, also tried to change the air version for project but unable to change it ( how can I change it from 4 to 3.9 or so? ) as it was the problem with starling and thats how I build apk there

\flambe-demos-master\particles\build.cache\air\config-android.xml: error 102: Invalid namespace http://ns.adobe.com/air/application/4.0

Please help. Thanks.

**Comment by quinnhoener** [comment]
I'm having this exact same problem. I'm on:
Flambe 4.1.0
AIR SDK 17.0.0.144
Mac OSX 10.10.2

I've tried by using a new flambe project and also using the https://github.com/aduros/flambe-demos/tree/master/extensions project. 

Thanks for any help.

**Comment by quinnhoener** [comment]
Ok, for some reason even though I installed the latest AIR SDK, running adt -version in Terminal is saying it's still set to 3.5.0... Trying to figure out how to point that to the correct adt version.

**Comment by quinnhoener** [comment]
Fixed it! For anyone else who has issues, I was trying to replace the adt and adl executables in my usr/local/bin/ folder, since that's where I previously had them. But for some reason it wouldn't update to the latest version. So I deleted the ones in /usr/local/bin/ and just added a new folder to my $PATH on my machine to a new folder where the AdobeAIRSDK folder is.
